module.exports = {
    SP_MATRICES_001: 'SP_MATRICES_001',
    SP_MATRICES_002: 'SP_MATRICES_002',
    s_BM_CATEGORIAS_DATOS: 's_BM_CATEGORIAS_DATOS',
    s_BM_RIESGOS_DATOS: 's_BM_RIESGOS_DATOS',
    s_AC_MATRIZ_OC_CRUD: 's_AC_MATRIZ_OC_CRUD',
    s_AU_MATRIZ_OCR_CRUD: 's_AU_MATRIZ_OCR_CRUD',
    s_AU_MATRIZ_AC_CRUD: 's_AU_MATRIZ_AC_CRUD'
}