module.exports = { 
    BAD_REQUEST: 'BAD_REQUEST', 
    UNAUTHORIZED: 'UNAUTHORIZED', 
    OK_REQUEST: 'OK_REQUEST', 
    NOT_FOUND: 'NOT_FOUND', 
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
}
